# Starter pipeline
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'Azure Pass - Sponsorship(1)(08e6148f-1eb7-4c29-a59e-df2aff7be8a1)'
    subscriptionId: '08e6148f-1eb7-4c29-a59e-df2aff7be8a1'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'az30304a-labRG'
    location: 'East US'
    templateLocation: 'URL of the file'
    csmFileLink: 'https://github.com/Payalk11/myrg/blob/master/myrg/WindowsVirtualMachine.json'
    csmParametersFileLink: 'https://github.com/Payalk11/myrg/blob/master/myrg/WindowsVirtualMachine.parameters.json'
    deploymentMode: 'Complete'
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
